### ISSUE TITLE
Actor state desktop view is broken

### ISSUE THREAD

**Issue by jdpnielsen** [jdpnielsen/filmfaroeislands#11]
#10 

![image](https://cloud.githubusercontent.com/assets/8746698/18444930/8eb68d56-791b-11e6-8937-d90ab8d7f290.png)

![image](https://cloud.githubusercontent.com/assets/8746698/18444972/afc45aa0-791b-11e6-9b4c-96846fef5cc9.png)

**Comment by KasperAndersson** [comment]
Fixed in #10
