### ISSUE TITLE
Add locations modal

### ISSUE THREAD

**Issue by jdpnielsen** [jdpnielsen/filmfaroeislands#27]
@KasperAndersson Would you mind making this?

![02 location](https://cloud.githubusercontent.com/assets/8746698/18653602/47c4d554-7edb-11e6-849f-9af44257605b.jpg)

**Comment by KasperAndersson** [comment]
[#27/location-modal](https://github.com/jdpnielsen/filmfaroeislands/tree/%2327/location-modal)

**Comment by jdpnielsen** [comment]
Closed by #33
